import { AuthError } from './auth-security.js';
import type { PrismaClient } from './generated/prisma/client.js';
import { geocoder, limitGeocoding, type Address, type Geocoder } from './geocoding.js';

// Initial service coverage only; the rectangle is not an administrative boundary.
export const locationOptions = {
  country: { id: 'ET', name: 'Ethiopia' },
  region: { id: 'addis-ababa', name: 'Addis Ababa' },
  city: { id: 'addis-ababa-city', name: 'Addis Ababa' },
  subcities: [
    { id: 'addis-ketema', name: 'Addis Ketema' },
    { id: 'akaki-kality', name: 'Akaki Kality' },
    { id: 'arada', name: 'Arada' },
    { id: 'bole', name: 'Bole' },
    { id: 'gulele', name: 'Gulele' },
    { id: 'kirkos', name: 'Kirkos' },
    { id: 'kolfe-keranio', name: 'Kolfe Keranio' },
    { id: 'lideta', name: 'Lideta' },
    { id: 'nifas-silk-lafto', name: 'Nifas Silk Lafto' },
    { id: 'yeka', name: 'Yeka' },
    { id: 'lemi-kura', name: 'Lemi Kura' },
  ],
  bounds: { south: 8.8, north: 9.15, west: 38.6, east: 39.0 },
} as const;

export interface LocationInput {
  countryId: string;
  regionId: string;
  cityId: string;
  subcityId: string;
  latitude: number;
  longitude: number;
  confirmed: true;
  addressLanguage?: 'en' | 'am';
}
interface SavedLocation extends LocationInput { updatedAt: Date; address: Address | null }

export function locationInput(value: unknown): LocationInput {
  const invalid = () => new AuthError(400, 'INVALID_LOCATION', 'Choose an available location and confirm a map point inside the supported Addis Ababa area.');
  if (typeof value !== 'object' || value === null || Array.isArray(value)) throw invalid();
  const input = value as Record<string, unknown>;
  const keys = ['countryId', 'regionId', 'cityId', 'subcityId', 'latitude', 'longitude', 'confirmed'];
  if (Object.keys(input).some(key => !keys.includes(key) && key !== 'addressLanguage') || keys.some(key => !Object.hasOwn(input, key))
    || (Object.hasOwn(input, 'addressLanguage') && (typeof input['addressLanguage'] !== 'string' || !['en', 'am'].includes(input['addressLanguage'])))
    || input['countryId'] !== locationOptions.country.id
    || input['regionId'] !== locationOptions.region.id
    || input['cityId'] !== locationOptions.city.id
    || !locationOptions.subcities.some(subcity => subcity.id === input['subcityId'])
    || input['confirmed'] !== true
    || typeof input['latitude'] !== 'number' || !Number.isFinite(input['latitude'])
    || typeof input['longitude'] !== 'number' || !Number.isFinite(input['longitude'])) throw invalid();
  const { south, north, west, east } = locationOptions.bounds;
  const latitude = input['latitude'];
  const longitude = input['longitude'];
  // Validate before rounding so a just-outside point cannot enter the service area.
  if (latitude < south || latitude > north || longitude < west || longitude > east) throw invalid();
  return {
    countryId: locationOptions.country.id, regionId: locationOptions.region.id,
    cityId: locationOptions.city.id, subcityId: input['subcityId'] as string,
    latitude: Math.round(latitude * 1e6) / 1e6, longitude: Math.round(longitude * 1e6) / 1e6,
    confirmed: true,
    ...(Object.hasOwn(input, 'addressLanguage') ? { addressLanguage: input['addressLanguage'] as 'en' | 'am' } : {}),
  };
}

export async function readLocation(database: PrismaClient, accountId: string): Promise<SavedLocation | null> {
  const [location] = await database.$queryRaw<SavedLocation[]>`
    SELECT "countryId", "regionId", "cityId", "subcityId", latitude, longitude, confirmed, "updatedAt", address
    FROM akgebeya_foundation.account_location WHERE "accountId" = ${accountId}::uuid`;
  return location ?? null;
}

export async function saveLocation(database: PrismaClient, accountId: string, input: LocationInput, lookup: Geocoder = geocoder, signal?: AbortSignal): Promise<SavedLocation> {
  let address: Address | null = null;
  try {
    await limitGeocoding(database, accountId);
    address = (await lookup.reverse({ latitude: input.latitude, longitude: input.longitude, language: input.addressLanguage ?? 'en' }, signal, accountId))?.address ?? null;
  } catch { /* Coordinates remain usable when address data is unavailable; never reuse a stale label. */ }
  // The account key serializes concurrent writes; equal retries retain the original timestamp.
  // Geometry is generated by PostgreSQL from longitude/latitude, never accepted from a client.
  const [location] = await database.$queryRaw<SavedLocation[]>`
    INSERT INTO akgebeya_foundation.account_location AS current
      ("accountId", "countryId", "regionId", "cityId", "subcityId", latitude, longitude, confirmed, address)
    VALUES (${accountId}::uuid, ${input.countryId}, ${input.regionId}, ${input.cityId},
      ${input.subcityId}, ${input.latitude}, ${input.longitude}, ${input.confirmed}, ${address === null ? null : JSON.stringify(address)}::jsonb)
    ON CONFLICT ("accountId") DO UPDATE SET
      "countryId" = EXCLUDED."countryId", "regionId" = EXCLUDED."regionId",
      "cityId" = EXCLUDED."cityId", "subcityId" = EXCLUDED."subcityId",
      latitude = EXCLUDED.latitude, longitude = EXCLUDED.longitude, confirmed = EXCLUDED.confirmed,
      address = EXCLUDED.address,
      "updatedAt" = CASE WHEN (current."countryId", current."regionId", current."cityId",
        current."subcityId", current.latitude, current.longitude, current.confirmed)
        IS DISTINCT FROM (EXCLUDED."countryId", EXCLUDED."regionId", EXCLUDED."cityId",
          EXCLUDED."subcityId", EXCLUDED.latitude, EXCLUDED.longitude, EXCLUDED.confirmed)
        THEN clock_timestamp() ELSE current."updatedAt" END
    RETURNING "countryId", "regionId", "cityId", "subcityId", latitude, longitude, confirmed, "updatedAt", address`;
  if (!location) throw new Error('Location save returned no record');
  return location;
}
